# Generated by Django 2.2.3 on 2019-07-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190703_0144'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event_item',
            table='event_item',
        ),
    ]
