# Generated by Django 2.2.3 on 2019-07-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190703_1424'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event_item',
            table='items',
        ),
    ]
